BabylonJS/Exporters

- Unity 5/EditorToolkit/Assets/Babylon/Scripts/Edit/ShaderInterface.cs
- Unity 5/EditorToolkit/Assets/Babylon/Scripts/SceneBuilder.Materials.cs
- Unity 5/EditorToolkit/Assets/Babylon/Shaders/Unity/UnityMetallic.shader
- Unity 5/EditorToolkit/Assets/Babylon/Shaders/Unity/UnityRoughness.shader
- Unity 5/EditorToolkit/Assets/Babylon/Shaders/Unity/UnitySpecular.shader
Support Unity 2017.2 PBR - Standard - Standard Roughness - Standard
Specular Setups
> Unity 2017.2 PBR Setups

- Unity 5/EditorToolkit/Assets/Babylon/Scripts/ExporterWindow.cs
- Unity 5/EditorToolkit/Assets/Babylon/Scripts/SceneBuilder.Lights.cs
- Unity 5/EditorToolkit/Assets/Babylon/Scripts/SceneBuilder.Materials.cs
- Unity 5/EditorToolkit/Assets/Babylon/Scripts/Tools.cs
Auto Detect Default Node And TypeScript Runtime Compiler Locations
> Babylon Toolkit Update - Version 3.1.032 (Alpha)

- 3ds Max/Max2Babylon/Exporter/GLTFGlobalVertex.cs
>  Fix types of GLTFGlobalVertex

- 3ds Max/Max2Babylon/Exporter/BabylonExporter.Texture.cs
A bit more information for our artists!
> Texture warning messages

- 3ds Max/Max2Babylon/Exporter/BabylonExporter.Mesh.cs
Fix for #102. 
This has given us the results we expect.
> Fix #102: wrong normals when exported with a non-identity pivot

- 3ds Max/Max2Babylon/Exporter/BabylonExporter.cs
- 3ds Max/Max2Babylon/Forms/ExporterForm.cs
> fix invalid rank exception; print a warning message for it instead

- 3ds Max/Max2Babylon/Forms/ExporterForm.cs
export tangents option wasn't serialized; now it is
> export tangents option wasn't serialized; now it is

- 3ds Max/CHANGELOG.md
- 3ds Max/Max2Babylon/ExportParameters.cs
- 3ds Max/Max2Babylon/Exporter/BabylonExporter.cs
- 3ds Max/Max2Babylon/Forms/ExporterForm.Designer.cs
- 3ds Max/Max2Babylon/Forms/ExporterForm.cs
**Implemented changes:**
- Added option to not export materials (https://github.com/BabylonJS/Exporters/issues/362)
> Material export toggle

- 3ds Max/Max2Babylon/2015/Max2Babylon2015.csproj
- 3ds Max/Max2Babylon/2017/Max2Babylon2017.csproj
- 3ds Max/Max2Babylon/2018/Max2Babylon2018.csproj
- 3ds Max/Max2Babylon/2019/Max2Babylon2019.csproj
Resolves https://github.com/BabylonJS/Exporters/issues/325
> 3dsMax: update visual studio build to support release mode

- 3ds Max/Max2Babylon/Exporter/BabylonExporter.cs
- 3ds Max/Max2Babylon/Forms/ExporterForm.cs
To allow another plugin to be notified when an export operation is done I use max notification.
In my case, I added to notify to perforce that new file are added/edited and in this, I can automatically mark for add/ mark for edit using my in house plugin
> Added max notification , to allow integration with version control 

- 3ds Max/Max2Babylon.sln
- 3ds Max/Max2Babylon/2015/Max2Babylon2015.csproj
- 3ds Max/Max2Babylon/2017/Max2Babylon2017.csproj
- 3ds Max/Max2Babylon/2018/Max2Babylon2018.csproj
- 3ds Max/Max2Babylon/2019/Max2Babylon2019.csproj
- 3ds Max/Max2Babylon/OnPostBuild.bat
- 3ds Max/Max2Babylon/OnPreBuild.bat
move project export configuration to a bat file to allow customization
post build and prebuild try to run 3dsmax  when working in debug mode to easily test directly in max
> project setup changed to use a bat file

- 3ds Max/Max2Babylon/2015/Max2Babylon2015.csproj
- 3ds Max/Max2Babylon/2017/Max2Babylon2017.csproj
- 3ds Max/Max2Babylon/2018/Max2Babylon2018.csproj
- 3ds Max/Max2Babylon/2019/Max2Babylon2019.csproj
- 3ds Max/Max2Babylon/Exporter/BabylonExporter.GLTFExporter.Animation.cs
- 3ds Max/Max2Babylon/Exporter/BabylonExporter.GLTFExporter.Mesh.cs
- 3ds Max/Max2Babylon/Exporter/BabylonExporter.GLTFExporter.Skin.cs
- 3ds Max/Max2Babylon/Exporter/BabylonExporter.GLTFExporter.cs
- 3ds Max/Max2Babylon/Exporter/BabylonExporter.cs
- 3ds Max/Max2Babylon/Extensions/ScaleSystem.cs
- 3ds Max/Max2Babylon/Tools/Tools.cs
Added support for different unit scale system in max file #70
> Unit scale support

- 3ds Max/Max2Babylon/2015/Max2Babylon2015.csproj
- 3ds Max/Max2Babylon/2017/Max2Babylon2017.csproj
- 3ds Max/Max2Babylon/2018/Max2Babylon2018.csproj
- 3ds Max/Max2Babylon/2019/Max2Babylon2019.csproj
- 3ds Max/Max2Babylon/OnPostBuild.bat
modified bat file to use env_variable instead of absolute path
> Project setup

- 3ds Max/Max2Babylon/Exporter/BabylonExporter.Mesh.cs
- 3ds Max/Max2Babylon/Exporter/BabylonExporter.Skeleton.cs
Fixes #489 
@Selmar 
Exporting bones of a mesh there is no need to export the entire hierarchy with them
> fix skin node hierarchy

- 3ds Max/Max2Babylon/Exporter/AnimationGroup.cs
- 3ds Max/Max2Babylon/Forms/AnimationForm.cs
- 3ds Max/Max2Babylon/Forms/AnimationForm.designer.cs
added the possibility to merge exported animation group
added multiselection on delete/export 
added clean button to remove empty animation group
> AnimationGroup multiselection, merge, clean features

- 3ds Max/Max2Babylon/BabylonAnimationActionItem.cs
- 3ds Max/Max2Babylon/Forms/AnimationForm.cs
> Get animation group by node

- 3ds Max/Max2Babylon/Exporter/AnimationGroup.cs
- 3ds Max/Max2Babylon/Forms/AnimationForm.designer.cs
some buttons in the designer were missing.
a control was causing a null reference exception
> fix merge, clean button after last merge issues

- 3ds Max/Max2Babylon/Exporter/BabylonExporter.Material.cs
- 3ds Max/Max2Babylon/Exporter/BabylonExporter.Texture.cs
- SharedProjects/BabylonExport.Entities/BabylonExport.Entities.projitems
- SharedProjects/BabylonExport.Entities/BabylonPBRClearCoat.cs
- SharedProjects/BabylonExport.Entities/BabylonPBRMaterial.cs
- SharedProjects/BabylonExport.Entities/BabylonPBRMetallicRoughnessMaterial.cs
> Max support for coating

- Maya/Exporter/BabylonExporter.Material.cs
- Maya/Exporter/BabylonExporter.Texture.cs
- SharedProjects/BabylonExport.Entities/BabylonPBRClearCoat.cs
> Add coating to maya

- 3ds Max/Max2Babylon/Exporter/BabylonExporter.Mesh.cs
Addresses #541.
Change to max mesh exporter logic, treat as unique instances that do not share materials. Refactor of ExportMesh, made helper functions ExportMasterMesh and ExportInstanceMesh for mesh export cases.
> Naively support 3dsMax mesh instances with different materials.

- 3ds Max/Max2Babylon/ExportParameters.cs
- 3ds Max/Max2Babylon/Exporter/BabylonExporter.Material.cs
- 3ds Max/Max2Babylon/Exporter/BabylonExporter.cs
- 3ds Max/Max2Babylon/Forms/ExporterForm.Designer.cs
- 3ds Max/Max2Babylon/Forms/ExporterForm.cs
- 3ds Max/Max2Babylon/Forms/ExporterForm.resx
- 3ds Max/Max2Babylon/MaxScriptManager.cs
- Maya/Exporter/BabylonExporter.Material.cs
- Maya/Exporter/BabylonExporter.cs
- Maya/Forms/ExporterForm.Designer.cs
- Maya/Forms/ExporterForm.cs
- Maya/Forms/ExporterForm.resx
- Maya/Maya2Babylon2019.csproj
- SharedProjects/BabylonExport.Entities/BabylonPBRMaterial.cs
Simplify iterations in max by adding a couple of flags to prevent default lighting, allow preprocess env textures and switch to full PBRMaterial for easier troubleshooting.
> Maya and Max PBR Workflow options

- 3ds Max/Max2Babylon/Exporter/BabylonExporter.cs
- 3ds Max/Max2Babylon/Exporter/MaxGLTFMaterialExporter.cs
- 3ds Max/Max2Babylon/Forms/ExporterForm.cs
- 3ds Max/Max2Babylon/MaxScriptManager.cs
- Maya/Exporter/BabylonExporter.Texture.cs
- SharedProjects/Babylon2GLTF/GLTFExporter.Material.Optimizer.cs
- SharedProjects/Babylon2GLTF/GLTFExporter.Material.cs
- SharedProjects/BabylonExport.Entities/ExportParameters.cs
re-add custom material exporter initializer, create MaxGLTFMaterialExporter on gltf export start.
Addresses #568
> Re-enable custom GLTF material exporters

- 3ds Max/Max2Babylon/Tools/Tools.cs
I forgot to automatically add the node with animation infos inside the container in my last commit
> fix minor issue creating helper node for containers animation

- 3ds Max/Max2Babylon/Forms/ExporterForm.cs
just a missing lines from the previous refactoring
> do not optimize animation preference was not loaded opening the expter panel

- 3ds Max/Max2Babylon/2015/Max2Babylon2015.csproj
- 3ds Max/Max2Babylon/2017/Max2Babylon2017.csproj
- 3ds Max/Max2Babylon/2018/Max2Babylon2018.csproj
- 3ds Max/Max2Babylon/2019/Max2Babylon2019.csproj
- 3ds Max/Max2Babylon/2019/packages.config
- 3ds Max/Max2Babylon/Forms/ExporterForm.Designer.cs
- 3ds Max/Max2Babylon/Forms/ExporterForm.cs
- 3ds Max/Max2Babylon/Forms/ExporterForm.resx
- 3ds Max/Max2Babylon/Forms/MultiExportForm.Designer.cs
- 3ds Max/Max2Babylon/Forms/MultiExportForm.cs
- 3ds Max/Max2Babylon/Forms/MultiExportForm.resx
- 3ds Max/Max2Babylon/MaxScriptManager.cs
- 3ds Max/Max2Babylon/OnPostBuild.bat
- 3ds Max/Max2Babylon/Tools/Tools.cs
- SharedProjects/Utilities/PathUtilities.cs
Revert "replaced FolderBrowseDialog with the extended FileDialog of WindowsAPICodepack"
This reverts commit dbe0444edae1b64722f2c375a350f0202d7047c7.
> Revert commit dbe0444 - change File Browser Form

- 3ds Max/Max2Babylon/2015/Max2Babylon2015.csproj
- 3ds Max/Max2Babylon/2017/Max2Babylon2017.csproj
- 3ds Max/Max2Babylon/2018/Max2Babylon2018.csproj
- 3ds Max/Max2Babylon/2019/Max2Babylon2019.csproj
- 3ds Max/Max2Babylon/2019/packages.config
- 3ds Max/Max2Babylon/Forms/ExporterForm.Designer.cs
- 3ds Max/Max2Babylon/Forms/ExporterForm.cs
- 3ds Max/Max2Babylon/Forms/ExporterForm.resx
- 3ds Max/Max2Babylon/Forms/MultiExportForm.Designer.cs
- 3ds Max/Max2Babylon/Forms/MultiExportForm.cs
- 3ds Max/Max2Babylon/Forms/MultiExportForm.resx
- 3ds Max/Max2Babylon/MaxScriptManager.cs
- 3ds Max/Max2Babylon/OnPostBuild.bat
- 3ds Max/Max2Babylon/Tools/Tools.cs
- SharedProjects/Utilities/PathUtilities.cs
Revert #588 since it did not cause regression #587 
"Revert "replaced FolderBrowseDialog with the extended FileDialog of WindowsAPICodepack""
This reverts commit 3b3cbc5a0d9de2340692b29c921bece343099df9.
> Revert #588

- SharedProjects/Babylon2GLTF/GLTFExporter.Animation.cs
#600 
revert on GLTFExporter.Animation.cs 
AnimationgGoups were assigned to the wrong nodes
> animations were not linked to correct nodes

- 3ds Max/Max2Babylon/Exporter/BabylonExporter.Texture.cs
Fix to nullreference of baseColorTexture file extension, reorganized export code for clarity.
> Fix null reference when exporting material with no alpha map and no base color map.

- 3ds Max/Max2Babylon/Exporter/AnimationGroup.cs
- 3ds Max/Max2Babylon/Tools/Tools.cs
There was a minimal issue with _ID_ suffix, sorry
> Fix bug on suffix ID assignation

- 3ds Max/Max2Babylon/Exporter/BabylonExporter.ExportItem.cs
- 3ds Max/Max2Babylon/Forms/LayerSelector.cs
- 3ds Max/Max2Babylon/Forms/MultiExportForm.cs
single node export was not possible after layer export integration
fix bug that was duplicating layers in multiexport panel
> fix bug on MultiExport panel

- 3ds Max/Max2Babylon/Exporter/BabylonExporter.cs
- 3ds Max/Max2Babylon/Exporter/MaxExportParameters.cs
- 3ds Max/Max2Babylon/Forms/ExporterForm.Designer.cs
- 3ds Max/Max2Babylon/Forms/ExporterForm.cs
- 3ds Max/Max2Babylon/Loader.cs
- 3ds Max/Max2Babylon/Tools/Tools.cs
This is just a first pass,
Aniamtion group need still to be specified in the target file, 
I will add support for Xref Animation Group in a second pass
Added support for xref reference trough  hold fetch logic like we did for containers
changed style of main babylon window to "sizeable" to allow to reduce it manually
topmost true combined with new win style avoid hold fetch glitch on winform panel
> Support for Xref

- 3ds Max/Max2Babylon/Exporter/BabylonExporter.ExportItem.cs
- 3ds Max/Max2Babylon/Forms/ExporterForm.Designer.cs
- 3ds Max/Max2Babylon/Forms/ExporterForm.cs
- 3ds Max/Max2Babylon/Forms/LayerSelector.cs
- 3ds Max/Max2Babylon/Forms/MultiExportForm.Designer.cs
- 3ds Max/Max2Babylon/Forms/MultiExportForm.cs
as explained in #620 
I haven't linked the layer export feature to the single export page.
It is useless and I will not do it probably.
I prefer to work on something more important.
For this PR I just made the layer visibility management features 
and made a polish pass on the whole Layer exporter feature.
> Layer exporter improvements

- 3ds Max/Max2Babylon/Forms/ExporterForm.cs
sorry in the layer improvements I forget to add this null reference check that was causing a regression
> missing null reference check

- 3ds Max/Max2Babylon/Exporter/BabylonExporter.IMaterialExporter.cs
- 3ds Max/Max2Babylon/Exporter/BabylonExporter.cs
- 3ds Max/Max2Babylon/Forms/ExporterForm.Designer.cs
- 3ds Max/Max2Babylon/Forms/ExporterForm.cs
- 3ds Max/Max2Babylon/Tools/Tools.cs
- SharedProjects/BabylonExport.Entities/ExportParameters.cs
The flatten hierarchy has been rewritten to work without the preprocess system
With a huge scene of thousend of nodes, it was a pain to wait for a file Hold/Fetch
Also, there is completely compatibility with multi export
Flatten algorithm time is faster
> Flatten feature optimization

- 3ds Max/Max2Babylon/2015/Max2Babylon2015.csproj
- 3ds Max/Max2Babylon/2017/Max2Babylon2017.csproj
- 3ds Max/Max2Babylon/2018/Max2Babylon2018.csproj
- 3ds Max/Max2Babylon/2019/Max2Babylon2019.csproj
- 3ds Max/Max2Babylon/2020/Max2Babylon2020.csproj
- 3ds Max/Max2Babylon/BabylonLoadAnimationFromContainers.cs
- 3ds Max/Max2Babylon/BabylonLoadAnimations.cs
- 3ds Max/Max2Babylon/BabylonSaveAnimationToContainers.cs
- 3ds Max/Max2Babylon/BabylonStoreAnimations.cs
- 3ds Max/Max2Babylon/Exporter/AnimationGroup.cs
- 3ds Max/Max2Babylon/Exporter/BabylonExporter.cs
- 3ds Max/Max2Babylon/GlobalUtility.cs
- 3ds Max/Max2Babylon/MaxScriptManager.cs
- 3ds Max/Max2Babylon/Tools/Tools.cs
As with containers on source scene in the action menu StoreAnimation groups
Merge/link scene in a master scene
Click on action menu Load Animation Groups
If an animation group is already there with the same name, the two animation groups are merged
> AnimationGroup support xrefObject and merged scene

- 3ds Max/Max2Babylon/Exporter/BabylonExporter.Mesh.cs
- 3ds Max/Max2Babylon/Exporter/GlobalVertex.cs
- Maya/Exporter/BabylonExporter.Mesh.cs
- Maya/Exporter/GlobalVertex.cs
proposed fix for #648
Fix to regression caused by #647, modified hashset addition to use properly indexed vertex, created GlobalVertex copy constructor
> Fix vertex optimization regression.

- 3ds Max/Max2Babylon/Tools/Tools.cs
minimal issue fix calculating time range
> time range calculation fix

- 3ds Max/Max2Babylon/Exporter/BabylonExporter.cs
- 3ds Max/Max2Babylon/Forms/ExporterForm.cs
- 3ds Max/Max2Babylon/Tools/LayerUtilities.cs
- 3ds Max/Max2Babylon/Tools/Tools.cs
Exporter wasn't able to merge multiple Xref
Exporting multi export (layer based) we should force children of a layer to be visible
> Bugfix generic: Xref, Multi Export

- 3ds Max/Max2Babylon/Exporter/BabylonExporter.Mesh.cs
- Maya/Exporter/BabylonExporter.Animation.cs
- Maya/Exporter/BabylonExporter.Mesh.cs
- Maya/Exporter/BabylonExporter.Skeleton.cs
- SharedProjects/Babylon2GLTF/GLTFExporter.Animation.cs
- SharedProjects/BabylonExport.Entities/BabylonMorphTargetManager.cs
fix Maya animation group issue where some bones are excluded from animation group inclusion due to improper hierarchy data. partial fix of #657.
> Fix Maya glTF export mesh skinning issue, inaccurate animation group keyframes

- 3ds Max/Max2Babylon/Exporter/BabylonExporter.cs
> Reconnect root node scaling parameter to scene export logic

- 3ds Max/Max2Babylon/Exporter/BabylonExporter.cs
- Maya/Exporter/BabylonExporter.cs
Add try-catch block around node processing logic, and print an exception handling message with exception outer and inner messages
Addressing #677
> Add exception guards in node processing logic

- BabylonJS_Installer/BabylonJS_Installer/Downloader.cs
- BabylonJS_Installer/BabylonJS_Installer/MainForm.cs
> Remove generated BabylonCleanUp.ms on install

- 3ds Max/Max2Babylon/MaxScriptManager.cs
we should refactor all these parameters as constant value asap
for now, I just added some max script parameters
> add missing maxscript parameters

- BabylonJS_Installer/BabylonJS_Installer/BabylonJS_Installer.csproj
- BabylonJS_Installer/BabylonJS_Installer/Downloader.cs
- BabylonJS_Installer/BabylonJS_Installer/MainForm.Designer.cs
Update installer version to 1.3.1, add support for installer to no longer exception when processing a directory inside of a ZipFile.
> Installer version 1.3.1. Support AETemplate and NETemplate subfolder inside published drop.

- 3ds Max/Max2Babylon/Exporter/BabylonExporter.cs
- SharedProjects/Babylon2GLTF/GLTFExporter.cs
just a more detailed way to log export time
> debugger info improvement

- 3ds Max/Max2Babylon/Exporter/MaxGLTFMaterialExporter.cs
- SharedProjects/Babylon2GLTF/GLTFExporter.Texture.cs
- SharedProjects/Babylon2GLTF/GLTFExporter.cs
This change refactors the gltf exporter texture writing logic to properly respect the exporter parameter "write textures" when glb export is enabled. in addition, the TryWriteTexture function was refactored to only be used in the custom Max GLTF material export abstraction.
> Modify GLTF exporter to respect "write texture" export parameter option

- 3ds Max/Max2Babylon/Exporter/BabylonExporter.Texture.cs
Modified BaseColorAlphaTexture generation to give combined textures a unique ID and output name.
> Give generated BaseColor + Alpha textures a unique internal ID and filename

- 3ds Max/Max2Babylon/Exporter/BabylonExporter.cs
Fix issue #696 for 3dsMax
See PR #752 for Maya.
> [3dsMax] Fix light rotation in glTF

- SharedProjects/GltfExport.Entities/GLTF.cs
- SharedProjects/GltfExport.Entities/GLTFAccessor.cs
- SharedProjects/GltfExport.Entities/GLTFAnimation.cs
- SharedProjects/GltfExport.Entities/GLTFAnimationSampler.cs
- SharedProjects/GltfExport.Entities/GLTFAsset.cs
- SharedProjects/GltfExport.Entities/GLTFBuffer.cs
- SharedProjects/GltfExport.Entities/GLTFCamera.cs
- SharedProjects/GltfExport.Entities/GLTFImage.cs
- SharedProjects/GltfExport.Entities/GLTFLight.cs
- SharedProjects/GltfExport.Entities/GLTFMaterial.cs
- SharedProjects/GltfExport.Entities/GLTFMesh.cs
- SharedProjects/GltfExport.Entities/GLTFMeshPrimitive.cs
- SharedProjects/GltfExport.Entities/GLTFNode.cs
- SharedProjects/GltfExport.Entities/GLTFPBRMetallicRoughness.cs
- SharedProjects/GltfExport.Entities/GLTFProperty.cs
- SharedProjects/GltfExport.Entities/GLTFSampler.cs
- SharedProjects/GltfExport.Entities/GLTFScene.cs
- SharedProjects/GltfExport.Entities/GLTFSkin.cs
- SharedProjects/GltfExport.Entities/GLTFTexture.cs
- SharedProjects/GltfExport.Entities/GLTFTextureInfo.cs
- SharedProjects/GltfExport.Entities/IGLTFMaterialExporter.cs
Follow up to #763 after testing.
> Fix serializing of default values

- 3ds Max/Max2Babylon/Tools/LayerUtilities.cs
just added a utility function to get all node of an "IIlayer" object
> added utility to get all node in a layer

- 3ds Max/Max2Babylon/BabylonExportActionItem.cs
- 3ds Max/Max2Babylon/Exporter/AnimationGroup.cs
- 3ds Max/Max2Babylon/Tools/Tools.cs
animation group panel performance improvement
exporter window attached to max window
> performace improvement

- SharedProjects/Babylon2GLTF/GLTFExporter.Texture.cs
> Modify gltf texture export to properly set mimetype before glb export.

- SharedProjects/GltfExport.Entities/GLTFAnimationSampler.cs
Fix for gltf animation sampler serialization, changed serialization to use assigned string value of enum, and added attribute for string conversion.git status
> Fix gltf animation interpolation mode serialization

- 3ds Max/Max2Babylon/Forms/ExporterForm.Designer.cs
- 3ds Max/Max2Babylon/Forms/ExporterForm.cs
tweak position of some UI elements to hide scrollviewer bar for FHD resolutions.
add behavior to switch to log view when export button is pressed.
> export form UI tweaks

- 3ds Max/Max2Babylon/Exporter/BabylonExporter.Animation.cs
- 3ds Max/Max2Babylon/Exporter/BabylonExporter.cs
fix for animation optimization logic that used scene root attribute for animation optimization, overriding supplied export parameters.
> Fix overriding of export parameter "optimizeAnimations"

- Maya/MELScripts/exportScriptExemple.mel
- Maya/MayaPlugin.cs
- SharedProjects/BabylonExport.Entities/ExportParameters.cs
Rearrange export parameters according to addition date, add export parameters to MELscript MayaPlugin, update sample script
> Expose new Export parameters to MELscript plugin

- SharedProjects/Babylon2GLTF/GLTFExporter.AbstractMesh.cs
This might be too specific to our needs, but seems valid enough to issue a warning if the node name gets changed.
> Add warning when node name changes

- Maya/Exporter/GlobalVertex.cs
https://github.com/BabylonJS/Exporters/issues/861
Some extra checks incase something is null.
Slightly different on what was talked about but it should cover the cases with less code.
> add null checks

- Maya/Exporter/GlobalVertex.cs
Reverts BabylonJS/Exporters#864
> Revert "add null checks"

- Maya/Exporter/GlobalVertex.cs
https://github.com/BabylonJS/Exporters/issues/861
https://github.com/BabylonJS/Exporters/pull/864
Some checks so an exception isn't thrown.
> Check null verts

- 3ds Max/Max2Babylon/Exporter/BabylonExporter.Mesh.cs
In 3DSMax, right-click on an object -> object properties -> user defined tab
As free text, add:
`extras = <a strigified JSON>`
where `<a strigified JSON>` is a JSON object written as a string.
Eg:
`extras = { "my_prop":"the_value", "another_prop": true, "a_sub_object": {"an_int":14, "an_array":[12.8, {"obj_in_array": true}]}}`
Then, while exporting as glTF, the object mesh will have an `"extras"` key containing the JSON object:
```
"extras": {
"my_prop": "the_value",
"another_prop": true,
"a_sub_object": {
"an_int": 14,
"an_array": [
12.8,
{
"obj_in_array": true
}
]
}
}
```
Tested with 3DSMax 2018 so far
> Add user defined properties "extras" to mesh's metadata

- 3ds Max/Max2Babylon/Exporter/BabylonExporter.Material.cs
- SharedProjects/Babylon2GLTF/GLTFExporter.Material.Optimizer.cs
fix  #879. test for re-use of Max Attribute. Fix null check for texture optimization.
> Unknown system error during export to glb 

- Maya/Exporter/GlobalVertex.cs
- SharedProjects/Babylon2GLTF/GLTFExporter.Animation.cs
- SharedProjects/Babylon2GLTF/GLTFExporter.Mesh.cs
- SharedProjects/Utilities/TextureUtilities.cs
fixes #885 
I also included a change which allows us to use some symbol definitions to suppress the use of two libraries which we're not interested in and don't want to ship.
> Switch normals based on normals being used

- SharedProjects/Babylon2GLTF/GLTFExporter.Animation.cs
Allow morph to be exported within Animation group fix #889
Make the AnimationGroup export and Animation export using the same code path.
> Allow Morph to be exported within animation group 

- Maya/Exporter/BabylonExporter.CustomAttributes.cs
- Maya/Exporter/GlobalVertex.cs
- Maya/Tools/Tools.cs
- SharedProjects/Babylon2GLTF/GLTFExporter.Mesh.cs
fix #861 and fix #874 and fix #822, fix #873. Update test into GlobalVertex.Equals
> avoiding null exception when trying to optimize vertices

- Maya/Exporter/BabylonExporter.Animation.cs
- Maya/Exporter/BabylonExporter.Mesh.cs
- SharedProjects/Babylon2GLTF/GLTFExporter.Mesh.cs
Stabilize export when morph not exported. Fix #900 .
> check for null pointers

- Maya/Exporter/BabylonExporter.Mesh.cs
Add support for deleted Morph target (which is 90% of cases) while target must be, by design and maya documentation, only used at design time. fix #902
> Maya : rebuild deleted morph target

- 3ds Max/Max2Babylon/Forms/ExporterForm.Designer.cs
Button are not displayed when screen resolution is low. Re-generate the form using 1920x1080 resolution, 100% scale.
> Update 3DSMax Exporter form for lower resolution

- Maya/Exporter/BabylonExporter.cs
- Maya/Tools/Tools.cs
> get correct maya version

- 3ds Max/Max2Babylon/Tools/Tools.cs
> update epsilon to smaller value

- BabylonJS_Installer/BabylonJS_Installer/MainForm.Designer.cs
Update Installer to support Max 2022 fix #948
> Update Installer to support Max 2022

- 3ds Max/Max2Babylon/MaterialScripts.cs
> Fix wrong arnold script

- BabylonJS_Installer/BabylonJS_Installer/MainForm.Designer.cs
- BabylonJS_Installer/BabylonJS_Installer/MainForm.cs
Add installation support for Maya2022.
> Add Maya 2022 support

- 3ds Max/Max2Babylon/Exporter/BabylonExporter.Mesh.cs
- 3ds Max/Max2Babylon/Exporter/BabylonExporter.Skeleton.cs
This reverts commit 80cfea556fcaca53692d2fa19f73a6fd668f979c.
> Revert "Add Root Node (#1028)"

- BabylonJS_Installer/BabylonJS_Installer/Downloader.cs
- BabylonJS_Installer/BabylonJS_Installer/MainForm.cs
Redesign the download pipeline - avoid ping - remove unecessary functions. close #615
> refactor installer pipeline - remove ping

- 3ds Max/Max2Babylon/2023/Max2Babylon2023.csproj
Update 2023 tag into release configuration
close #1046
> update 2023 tag

- 3ds Max/Max2Babylon/2023/Max2Babylon2023.csproj
Update 2023 tag for additional project configurations
> Update 2023 tag - 2

- BabylonJS_Installer/BabylonJS_Installer/Downloader.cs
- BabylonJS_Installer/BabylonJS_Installer/MainForm.Designer.cs
- BabylonJS_Installer/BabylonJS_Installer/MainForm.cs
Add maya 2023 to the installer. Also add a rename support for Maya plugin from xxx.dll to xxx.nll.dll. This fix #1054
> Maya 2023 installer

- 3ds Max/Max2Babylon/Exporter/BabylonExporter.CustomAttributes.cs
- 3ds Max/Max2Babylon/Exporter/BabylonExporter.ExportItem.cs
- 3ds Max/Max2Babylon/Exporter/BabylonExporter.Material.Pbr.cs
- 3ds Max/Max2Babylon/Exporter/BabylonExporter.Material.cs
- 3ds Max/Max2Babylon/Exporter/BabylonExporter.Mesh.cs
- 3ds Max/Max2Babylon/Exporter/BabylonExporter.Texture.cs
- 3ds Max/Max2Babylon/Exporter/BabylonExporter.cs
- 3ds Max/Max2Babylon/Exporter/GlobalVertex.cs
This merge request addresses two points:
- delete comment regarding a cesium hack, which has now become obsolete. Details:
https://github.com/CesiumGS/cesium/issues/11045
- minor clean-up regarding some white spaces
Thx!
> Small clean-up for models with negative scales

- Maya/Maya2Babylon.sln
- Maya/Maya2Babylon2024.csproj
Maya2Babylon2024 project was releasing binaries to 2023 folder.
> Fixed Maya 2024 build folder
