3ds Max/Max2Babylon/2015/Max2Babylon2015.csproj, 3ds Max/Max2Babylon/2017/Max2Babylon2017.csproj, 3ds Max/Max2Babylon/2018/Max2Babylon2018.csproj
Visual studio is x86 and can not show custom user controls if these controls have not been compiled in x86. This is an issue for the Animation groups, in which I have included a custom user control.
=> Revert PlatformTarget to AnyCPU

3ds Max/Max2Babylon/Exporter/BabylonExporter.Mesh.cs
Normalizing is necessary for meshes that have scale.
=> Normalize transformed normal

3ds Max/Max2Babylon/Exporter/BabylonExporter.GLTFExporter.cs, SharedProjects/GltfExport.Entities/GLTF.cs, SharedProjects/GltfExport.Entities/GLTFExtensions.cs, SharedProjects/GltfExport.Entities/GLTFProperty.cs, SharedProjects/GltfExport.Entities/GltfExport.Entities.projitems
Our custom material uses some extensions, so we need to be able to serialize them. These changes facilitate that.
Note: untested, because I only have max 2016 and I can't export with it in the current state.
=> support for extensions

3ds Max/Max2Babylon/Exporter/BabylonExporter.GLTFExporter.Texture.cs, 3ds Max/Max2Babylon/Exporter/BabylonExporter.Texture.cs
this was the default for every other file open I could find in the project (and is quite convenient)
As with the other pull request, could not test with the latest version (I've tested with an older version and it worked fine)
=> allow overwriting existing bitmaps when saving bitmaps

Maya/Forms/ExporterForm.cs, Maya/MayaPlugin.cs
Maya crashes when the plugin is _uninitialized_ but form is still open. - Uninitialized function closes the form now.
The (x) button at the top of the window - Override the default function to close the form.
**TODO:** State saving for crash handling and operating system shut down.
=> Safely close exporter

Blender/src/babylon-js/__init__.py, Blender/src/babylon-js/exporter_settings_panel.py, Blender/src/babylon-js/json_exporter.py
- Added seemingly missing mixin class for settings panel
- Removed the export active layers option
- Added an export scope option
- "All" option to export everything in the Blender scene, similar to previous functionality
- "Selected" option to export only selected objects
- "Visible" option which replaces the active layer option and also works with Blender's hide/show feature
=> Update blender exporter settings

Maya/Exporter/BabylonExporter.Node.cs
Currently the exporter uses the id of the first parent of a mesh as its parentId when exporting it. This results in meshes having an incorrect parent and therefore incorrect positions and rotations in the scene.
In the example scene I attached to issue #247 the Outliner shows the correct object hierarchy:
The exporter however exports both cubes as children of group1:
After the changes in this PR both cubes are exported and grouped correctly:
=> Use correct parent when exporting meshes. Fixes #247

3ds Max/Max2Babylon/Exporter/BabylonExporter.GLTFExporter.Mesh.cs, 3ds Max/Max2Babylon/Exporter/BabylonExporter.Mesh.cs, 3ds Max/Max2Babylon/Exporter/BabylonExporter.Skeleton.cs, 3ds Max/Max2Babylon/Exporter/BabylonExporter.cs
Changes:
- ignore bones with weight <= 0
- output vertex indices for vertices with >4 bones (gltf) or >8 bones (babylon)
- add check/warning for skins without bones (previously exception)
Possible issues:
- Many duplicate messages (see below image). This was already the case for babylon, before this pull request, the difference being I added this message for glTF and added the vertex index to the ouput. This begs the question: is there a reason for processing the same vertex index multiple times?
Already existing issues, even before this pull request:
- I can't get the skinned animation to play in babylon.js (the one that comes with "export & run), but it works correctly in three.js and the [online babylon viewer](https://sandbox.babylonjs.com/).
- The cone is invisible in three.js, but …
=> [Skin] vertex bone checks

Blender/src/babylon-js/exporter_settings_panel.py
This PR enables the "Write .manifest file" option by default.
=> set manifest file export enabled by default

3ds Max/Max2Babylon/Tools/Tools.cs
- Guids were not stored until requested the second time; this could potentially cause conflicts.
- Clarify an existing problem with Guid generation in comments (see below). Conflicts may still occur. This must be discussed (will create a separate issue).
=> Guid conflict bugfix mistake

3ds Max/CHANGELOG.md, 3ds Max/Max2Babylon/Exporter/BabylonExporter.cs
**Fixed bugs:**
- Fixed bug where babylonbinarymeshdata file was not getting copied to the output directory(https://github.com/BabylonJS/Exporters/issues/401)
=> export babylonbinarymeshdata file

3ds Max/Max2Babylon/2015/Max2Babylon2015.csproj, 3ds Max/Max2Babylon/2017/Max2Babylon2017.csproj, 3ds Max/Max2Babylon/2018/Max2Babylon2018.csproj, 3ds Max/Max2Babylon/2019/Max2Babylon2019.csproj, 3ds Max/Max2Babylon/Exporter/AnimationGroup.cs, 3ds Max/Max2Babylon/Exporter/BabylonExporter.GLTFExporter.Animation.cs, 3ds Max/Max2Babylon/Forms/AnimationGroupControl.cs, 3ds Max/Max2Babylon/Forms/MaxNodeTreeView.cs, 3ds Max/Max2Babylon/Forms/MultiExportForm.cs, 3ds Max/Max2Babylon/MaxScriptManager.cs, SharedProjects/GltfExport.Entities/GLTFImage.cs
I have just used the 3dsMax 2017 exporter in *Debug* mode, and it didn't compile due to too recent syntax used for out variables. I have fixed that and also add the possibility to use the exporter in Maxscript without having the dll files in `/bin/assemblies` folder (3dsMax makes a startup check in this folder to initialize plugin with their `Class_ID`).
Here are the different commits :
- Be able to initialize the Babylon Exporter plugin without any Autodesk startup checks.
- Do not use **C# 7.0** syntax for out variables to not break compatibility with older versions of .NET Frameworks used by 3dsMax.
- Use Autodesk standard environment variables instead of guessing drives in VS CSharp projects files.
=> Fix older 3dsMax versions compatibility

3ds Max/Max2Babylon/Exporter/BabylonExporter.GLTFExporter.Material.cs, Maya/Exporter/BabylonExporter.GLTFExporter.Material.cs
Proposed fix for #466. This modifies the existing Standard Shader specular/gloss to Metal/Roughness converter to use the Babylon engine's specular power -> roughness conversion heuristic.
This change removes the baseColor specular color calculations, and removes the assumptions of surface metallic properties based of its shininess.
=> Modify Maya/3ds Max GLTF Standard Shader Spec/gloss to PBRMetalRoughness converter

3ds Max/Max2Babylon/Exporter/BabylonExporter.Texture.cs
Workaround for #470.
Modified babylon base color texture creation to override the texture alpha mode based if the texture format does not have an alpha channel, and no transparency map was specified in material export.
=> Stop BabylonTexture from being created with alpha if no transparency map and texture does not have alpha channel

3ds Max/Max2Babylon/Max2Babylon_Package.py
Rudimentary python script to allow for quicker packaging workflow. currently retrieves dll binaries in each project build folder, and produces a .zip using the provided version number.
=> Max2Babylon packaging script

Maya/Maya2Babylon_Package.py
Rudimentary implementation of a Maya2Babylon project packaging script. Retrieves binaries from the release binary locations, renames the Maya2Babylon.dll file, and packages each version into a single .zip
=> Maya2Babylon packaging script.

3ds Max/Max2Babylon/Exporter/AnimationGroup.cs, 3ds Max/Max2Babylon/Forms/AnimationForm.cs
This pull request fixes a regression introduced by the merge conflict resolution of pull request #516 https://github.com/BabylonJS/Exporters/commit/88b37e6459159edb441a4fa7e7254ff4055498af 
which was later reverted via https://github.com/BabylonJS/Exporters/commit/61c69f89d15ff96e34bcc5b17ee820d471f50d20
This pull request Re-adds animation form related changes via https://github.com/BabylonJS/Exporters/commit/db4d9b2282c9fa46083ca42c30acc977dd42af19 and https://github.com/BabylonJS/Exporters/commit/74fe4fa949db63f6b91b343888270680c901a57e
=> Fix merge regression, Re-Add animation group selection

3ds Max/Max2Babylon/Forms/ExporterForm.cs, 3ds Max/Max2Babylon/Tools/Tools.cs
force ExportItem class to keep consistency with multiexport 
path of gltf is now stored relative to the project folder if project folder exists
=> Relative file path

3ds Max/CHANGELOG.md, 3ds Max/Max2Babylon/Exporter/BabylonExporter.cs, 3ds Max/Max2Babylon/Max2Babylon_Package.py, 3ds Max/readme.md, Maya/CHANGELOG.md, Maya/Exporter/BabylonExporter.cs, Maya/Maya2Babylon_Package.py, Maya/readme.md
Python script for Changelog auto-completion, retrieving datas from the Github.
- Changelog : Last version date added (needed for auto completion)
- Readme : Explaination added
- BabylonExporter.cs : Version number incremented by 0.1 for testing purpose
+ Merge from official repo in mine
=> Python script for Changelog auto-completion

3ds Max/Max2Babylon/ExportParameters.cs, 3ds Max/Max2Babylon/Exporter/BabylonExporter.ExportItem.cs, 3ds Max/Max2Babylon/Exporter/BabylonExporter.GLTFExporter.Texture.cs, 3ds Max/Max2Babylon/Exporter/BabylonExporter.cs, 3ds Max/Max2Babylon/Forms/ExporterForm.Designer.cs, 3ds Max/Max2Babylon/Forms/ExporterForm.cs, 3ds Max/Max2Babylon/Forms/ExporterForm.resx, 3ds Max/Max2Babylon/OnPreBuild.bat, 3ds Max/Max2Babylon/Tools/Tools.cs
users should be able to choose where to save textures, 
GLTFspecification doesn't allow us to save outside on top of the model folder, 
I display a warning in case the user does not respect this constraint
the same logic for the GLTF path (absolute/relative) is applied here.
I also made a mini improvement on the task kill function
=> Texture folder explicit

3ds Max/Max2Babylon/ExportParameters.cs, 3ds Max/Max2Babylon/Forms/ExporterForm.Designer.cs, 3ds Max/Max2Babylon/Forms/ExporterForm.cs, 3ds Max/Max2Babylon/MaxScriptManager.cs
InitParameters() now get all saved options inside max
added "Save" button to force options to be registered
added export function with no parameters to match Babylon
basically, the idea is to have the possibility to batch exporter operation
to do this we could call Export() from max script, but there was no match between Babylon configuration and the export function,
in other, it was the internal export button that registered user options,
passing from the max script means that user need the possibility to force to save the specified options
I also exposed the merge and import  animation group from a JSON file
There are many tools that need to be built around this exporter.
I'm planning to expose all the animation group methods soon
=> 3ds Max exporter batching improvements, add parameter saving, decouple export entrypoint from export button click callback.

3ds Max/Max2Babylon/Exporter/BabylonExporter.Texture.cs
Addressing regression introduced via #472. _getSpecialTexmap can dereference a null texMap if the material lacks a diffuse/specular/normal/specular map. Adding a null check in _getSpecialTexmap should fix this.
=> Fix _getSpecialTexmap null reference exception

3ds Max/Max2Babylon/Exporter/BabylonExporter.Texture.cs, SharedProjects/BabylonExport.Entities/BabylonQuaternion.cs
This pull request fixes the texture transform calculation, which previously applied rotation after calculating a texture transform with rotation and scaling, causing inaccurate texture transform components when the transform is decomposed.
This change correctly calculates a rotation quaternion when computing the transform matrix.
This also changes the export warning to reflect the limitations of the current KHR_texture_transform spec.
=> Fix texture transform calculation, Update Babylon texture export message

Maya/Exporter/BabylonExporter.GLTFExporter.Animation.cs
Fix for #549, for GLTF export add additional animation relevance check against entire animation channel if the initial check against the frame range isn't relevant
=> Make baked animations get excluded in export if they aren't relevant within group frame range.

Maya/Exporter/BabylonExporter.Mesh.cs
to improve the UX, update the warning message when a mesh is to be exported with skinning and morph target info to set the playhead to the proper frame so that the targets are exported properly.
=> Update skinning and morph target warning message

3ds Max/Max2Babylon/OnPostBuild.bat
Still requires the developer to change the postbuild event to pass 2016 to the script instead of 2015, but the rest is handled this way
=> [3dsMax][C#][PostBuild] Handle using Max 2016 with Max 2015 exporter version

Maya/Exporter/BabylonExporter.Animation.cs, Maya/Exporter/BabylonExporter.Camera.cs, Maya/Exporter/BabylonExporter.GLTFExporter.cs, Maya/Exporter/BabylonExporter.Mesh.cs, Maya/Exporter/BabylonExporter.Node.cs, Maya/Tools/Tools.cs, SharedProjects/BabylonExport.Entities/BabylonVector3.cs
This is intended to fix an issue where maya rotation animation keyframes are not accurately exported to Babylon. 
Reimplemented EulerAngle->Quaternion conversion to work with all 123 euler rotation sequences that are supported by Maya. Modified the animation keyframe export process to properly reverse rotation order when changing coordinate system from RHR to LHR.
=> Fix Maya rotation animation quaternion conversion

3ds Max/Max2Babylon/Exporter/BabylonExporter.Skeleton.cs
Fix for issue where 3dsMax skeletal animation groups are incomplete.
When we query for animated bones via BabylonExporter::ExportAnimationGroups, we query bones using the unique bone identifier of "{bone-node-guid}-bone" which allows .babylon format to identify bones separately from their nodes. 
This naming convention isn't used for gltf export, causing our refactor to expose this difference in behavior, and cauising our animation group to miss some bone animations. 
This was fixed by removing the divergence in behavior between the code paths, using the .babylon bone identifier notation for both export formats.
addressing #571
=> Fix 3dsMax glTF skeletal animation export.

3ds Max/Max2Babylon/Exporter/BabylonExporter.cs, 3ds Max/Max2Babylon/MaxScriptManager.cs
Fixing null reference exception when executing MaxScriptManager. Changed MaxScriptManager ExportParameters to use MaxExportParameters structure.
Addressing #577
=> Fix MaxScriptManager::Export() NullReference exception

SharedProjects/Babylon2GLTF/GLTFExporter.Material.cs, SharedProjects/Babylon2GLTF/GLTFExporter.Texture.cs
As a result of refactoring via #566, I improperly took changes introduced via https://github.com/BabylonJS/Exporters/commit/f97c29c0b12ffbbf736fa19f765eb678f0dba75c into the shared exporter.
As a result, we rename our textures in the Babylon->glTF export, which can negatively affect an asset pipeline due to duplication of textures. 
This appears to be related to #571, where texture paths are broken in exported scene.
This PR removes texture renaming in glTF export, preserving the original texture name provided to the exporter.
=> Remove glTF export texture renaming

readme.md
The general exporter documentation link did not exist so I added links to general installer info and glTF specific info for both Max and Maya. I also placed a direct link to the releases page here in the doc as a backup path to our releases.
=> Corrected links.

3ds Max/Max2Babylon/Exporter/BabylonExporter.Material.cs, 3ds Max/MaxScripts/BabylonMaterialAttributes.ms, SharedProjects/Babylon2GLTF/GLTFExporter.Material.cs, SharedProjects/BabylonExport.Entities/BabylonMaterial.cs, SharedProjects/BabylonExport.Entities/BabylonPBRMetallicRoughnessMaterial.cs, SharedProjects/BabylonExport.Entities/BabylonStandardMaterial.cs
Addressing #602  and #597, this PR proposes adding a float property to the "Babylon Attributes" material custom attribute container, and adds ability to redefine existing Babylon Attributes without data loss.
This PR also adds non-serialized transparencyMode and alphaCutoff fields to standard materials to persist to glTF export.
=> [3dsMax] Fix alphaTest attribute for standard material glTF export, add alphaCutoff control to babylon custom attributes.

SharedProjects/Babylon2GLTF/GLTFExporter.cs
This PR changes the description text of glTF exporter to use BabylonProducer info.
=> Fix gltf export description text

3ds Max/Max2Babylon/Exporter/AnimationGroup.cs, 3ds Max/Max2Babylon/Exporter/BabylonExporter.Animation.cs, 3ds Max/Max2Babylon/Exporter/BabylonExporter.cs, 3ds Max/Max2Babylon/Forms/AnimationForm.cs, 3ds Max/Max2Babylon/GlobalUtility.cs, 3ds Max/Max2Babylon/Tools/Tools.cs, SharedProjects/Babylon2GLTF/GLTFExporter.cs
I made a pass of optimization.
Animation group were looking for the node by GUID traversing all the scene over and over
Now this happens only if the node is not found in the GUID dictionary
This is the result before and after on two big files.
Consider that there are almost 500 animation groups for each file
There is still a lot of work to do especially exporting nodes, but this is just a first step
=> Optimization

3ds Max/Max2Babylon/BabylonAnimationActionItem.cs, 3ds Max/Max2Babylon/Forms/ExporterForm.cs
The Hold/Fetch logic combined with container export, modify the animation group panel and his serialization under the hood.
In this way, the panel is broken when the export is finished.
To easily fix this I just force the panel to close when export start
=> animation group panel must be closed when export begin

3ds Max/Max2Babylon/BabylonLoadAnimationFromContainers.cs, 3ds Max/Max2Babylon/BabylonSaveAnimationToContainers.cs, 3ds Max/Max2Babylon/Exporter/AnimationGroup.cs, 3ds Max/Max2Babylon/Exporter/BabylonExporter.cs, 3ds Max/Max2Babylon/Tools/Tools.cs
As requested from artists the load/save animation group is based on the selected container
This improves the experience of working with containers
Also now nested containers are supported
=> Load/Save AnimationGroup based on selection, support for nested container

3ds Max/Max2Babylon/Exporter/BabylonExporter.Animation.cs
I spent many hours to understand why this scene wasn't exporting
It because the scale go smaller and smaller creating NaN value on local matrix
just added a message to raise this as an error
[NAN value.zip](https://github.com/BabylonJS/Exporters/files/3677569/NAN.value.zip)
=> raise error when NAN value are found

Maya/Exporter/BabylonExporter.Camera.cs
Proposed fix for issue #643 where Maya exporter camera scale is null value Adds scaling assignment to BabylonCamera after TRS is retrieved from Maya
=> Fix null camera scale in gltf export

3ds Max/Max2Babylon/Exporter/BabylonExporter.cs, 3ds Max/Max2Babylon/Forms/AnimationGroupControl.cs, 3ds Max/Max2Babylon/Tools/Tools.cs
this is just a polish bug fix pull request
clean button was removing the animation group if the button was clicked just after the creation of the animation group 
the flatten hierarchy feature has been reduced to the multi export item, too many problems when launching from the generic exporter
the containers were merged when the use preexport process was false and the container checkbox was true
=> Bug fix animgroup, checkbox containers, flatten hierachy

3ds Max/Max2Babylon/2015/Max2Babylon2015.csproj, 3ds Max/Max2Babylon/2017/Max2Babylon2017.csproj, 3ds Max/Max2Babylon/2018/Max2Babylon2018.csproj, 3ds Max/Max2Babylon/2019/Max2Babylon2019.csproj, 3ds Max/Max2Babylon/2020/Max2Babylon2020.csproj, 3ds Max/Max2Babylon/Exporter/AnimationGroup.cs, 3ds Max/Max2Babylon/Forms/ObjectPropertiesForm.Designer.cs, 3ds Max/Max2Babylon/Forms/ObjectPropertiesForm.cs, 3ds Max/Max2Babylon/GlobalUtility.cs
two minimal improvement
- when a container is imported multiple times, the exporter merges those inside the scene and export.
There were duplicated material in scene and GLTF, now merging the container this duplication is removed
- Bake Node  Animation Enable/Disable logic has been moved to Babylon properties per object panel
=> move bake/no-bake node animation to babylon properties panel

SharedProjects/Babylon2GLTF/GLTFExporter.Animation.cs
Proposed fix for issue where exported gltf scenes have unnecessary input animation accessors. Added animation frame checks in GLTFExporter::ExportNodeAnimation, GLTFExporter::ExportBoneAnimation GLTFExporter::ExportMorphTargetWeightAnimation and GLTFExporter::_createAndPopulateInput
addressing #673
=> Fix empty input animation accessors in glTF export.

3ds Max/Max2Babylon/BabylonStoreAnimations.cs, 3ds Max/Max2Babylon/GlobalUtility.cs
in case a user load a scene with a closed container
and store the animation group of the container without opening the Babylon animation group, storing the animation group in the helper was failing because Guids dictionary was not initialized
=> fix issue on container helper creation with missing animation

3ds Max/Max2Babylon/Forms/ExporterForm.cs, 3ds Max/Max2Babylon/Tools/Tools.cs
Add "Unpatched version" warning to unsupported versions of Max2Babylon2020, and add version retrieval and formatting logic.
=> Add an additional warning for unsupported 3dsMax versions

3ds Max/Max2Babylon/Exporter/BabylonExporter.cs, 3ds Max/Max2Babylon/Forms/ExporterForm.cs, Maya/Exporter/BabylonExporter.cs, Maya/Forms/ExporterForm.cs
This change explicitly fails exporting the scene when an invalid scene scale factor or texture quality value is provided. The root node scaling print was also modified to include the factor value
Intended to help prevent issues like #687
=> Explicitly fail when invalid scaling value is provided.

SharedProjects/Babylon2GLTF/GLTFExporter.Light.cs
Addressing #689, change the gltf light serialization logic to convert light cone diametric angle to light radial angle.
=> Fix Babylon->GLTF light radius serialization

3ds Max/Max2Babylon/Forms/ExporterForm.Designer.cs, 3ds Max/Max2Babylon/Forms/ExporterForm.cs, SharedProjects/Babylon2GLTF/GLTFExporter.Texture.cs, SharedProjects/Babylon2GLTF/GLTFExporter.cs, SharedProjects/GltfExport.Entities/GLTFImage.cs, SharedProjects/Utilities/PathUtilities.cs
This should be ok
I also changed the UI as requested
#685
=> image uri fix

3ds Max/Max2Babylon/Exporter/AnimationGroup.cs
Materials were not merged correctly when coming from the same containers and a node with the same name was already in the master scene
=> fixed an issue with containers

3ds Max/Max2Babylon/Forms/ExporterForm.cs, 3ds Max/Max2Babylon/Tools/Tools.cs
a missing check was causing an object disposed exception when the user switched scene and had previously closed the exporter form
=> added missing check on scene change

3ds Max/Max2Babylon/Exporter/BabylonExporter.Mesh.cs
Fix for issue where exported babylon master meshes are reassigned their material GUID, and instances aren't considered proper instances when GUIDs are checked.
=> [3dsMax] Fix for duplicated instances that use a complex material

3ds Max/Max2Babylon/Exporter/BabylonExporter.cs
Add indented formatting if .babylon file is exported using debug exporter build for improved readability
similar to #705
=> Add debug formating to .babylon export

3ds Max/Max2Babylon/Exporter/BabylonExporter.cs, Maya/Exporter/BabylonExporter.cs
Since we moved to a CI pipeline, our old versioning system is no longer needed. This change replaces 1.4.0, and 1.5.0 with Custom.Build.Version, which will be replaced with the relevant version come packaging time.
addressing #712
=> Remove old version system, replace with Custom.Build.Version

3ds Max/Max2Babylon/Forms/ExporterForm.cs, Maya/Forms/ExporterForm.cs, SharedProjects/Babylon2GLTF/GLTFExporter.cs, SharedProjects/Utilities/Extensions.projitems, SharedProjects/Utilities/GLTFPipelineUtilities.cs
Fix draco compression gltf-pipeline launcher to no longer require a cmd script. Opens cmd prompt to execute "gltf-pipeline" npm module to check if gltf-pipeline is installed, and during compression
=> Refactor gltf-pipeline invoking logic

3ds Max/Max2Babylon/Exporter/BabylonExporter.ExportItem.cs, 3ds Max/Max2Babylon/Forms/ExporterForm.cs, 3ds Max/Max2Babylon/Forms/MultiExportForm.cs
the texture path of the multi export item was not resolved correctly converting absolute/relative path
=> fix an issue when texture path of multi export item where loaded/saved

3ds Max/Max2Babylon/MaxScriptManager.cs, 3ds Max/MaxScripts/Max2Babylon.ms
Expose optional parameter-less MaxScriptManager.Export() functions. Update Max2Babylon.ms sample script to show how to use logging functionality
=> Add "optional" paramaters to Max2Babylon Maxscript manager Export functions

Maya/Exporter/BabylonExporter.Texture.cs
Added extra logic to detect if a texture MPlug has a single channel plug connected to its children
=> Fix opacity texture detection if opacity is driven by texture alpha channel

3ds Max/Max2Babylon/Exporter/BabylonExporter.CustomAttributes.cs
a reference made trough max script based on the object name was exporting unnecessary dummy objects when two nodes with the same name were presents
=> fix null ref exception that was exporting unnecessary dummy nodes

SharedProjects/Babylon2GLTF/GLTFExporter.Texture.cs
title is pretty self explanatory, we previously still had the reference to the old GLTFTexture instance after finding a cached texture to use instead in the Dico cache
Addressing #735
=> Fix issue where GLTFTextureInfo still points to old GLTFTexture reference after cache hit

SharedProjects/Babylon2GLTF/GLTFExporter.Texture.cs
Fix to https://github.com/BabylonJS/Exporters/issues/739
Use name specified in parameter, if any, rather than input texture name.
=> Fix texture name when exporting to glTF

3ds Max/Max2Babylon/Exporter/BabylonExporter.Texture.cs, SharedProjects/Babylon2GLTF/GLTFExporter.Material.cs, SharedProjects/Babylon2GLTF/GLTFExporter.Texture.cs, SharedProjects/Utilities/TextureUtilities.cs
Combination of fixes:
Remove texture renaming during GLTF export -> output textures now retain the input texture name. followup to #739 
Fix GLTF KHR_Texture_transform export where texture is V inverted. Addressing #738 
Cleanup texture export, change texture format selection to retain texture extension
=> fix texture export issues

3ds Max/Max2Babylon/Exporter/BabylonExporter.Animation.cs, 3ds Max/Max2Babylon/Exporter/BabylonExporter.Mesh.cs, 3ds Max/Max2Babylon/Exporter/BabylonExporter.Skeleton.cs, 3ds Max/Max2Babylon/Exporter/BabylonExporter.cs, SharedProjects/Babylon2GLTF/GLTFExporter.Animation.cs, SharedProjects/Babylon2GLTF/GLTFExporter.Mesh.cs, SharedProjects/Babylon2GLTF/GLTFExporter.Skin.cs, SharedProjects/Babylon2GLTF/GLTFExporter.cs
Fix issue #746 
Add support for unit scaling when exporting to babylon. Previously only glTF export was supported.
Fix unit scaling when exporting to glTF.
In 3dsMax, when switching unit system, all objects in the scene are scaled accordingly.
Ex:
1 generic unit in a meter unit system is equal to 1m
After switching unit system to centimeter, the same 1 generic unit is equal to 1cm
=> [3dsMax] Fix and enhance support for unit scaling

Maya/Exporter/BabylonExporter.Animation.cs, Maya/Exporter/BabylonExporter.Mesh.cs, Maya/Exporter/BabylonExporter.Node.cs, Maya/Exporter/BabylonExporter.cs
Fix issues #694 and #687 
- Add support for unit scaling to export at meter scale (instead of centimeter as it used to)
- Refactor animation data retrieval from curves
In Maya, when switching unit system, objects in the scene are unaffected.
Ex:
1 generic unit in a meter unit system is equal to 1m
After switching unit system to centimeter, the same 1 generic unit is equal to 100cm
Thus, the support for unit scaling in Maya is straight forward.
All values retreived from Maya API are in centimeter.
The exporter is converting those values to meter.
The current unit system in Maya does not matter during export process.
Also, note that Maya documentation discourages to modify the unit system:
> You can change the default working units in Maya, which are in metric, but it is recommended to …
=> [Maya] Add support for unit scaling

Maya/Exporter/BabylonExporter.Camera.cs, Maya/Exporter/BabylonExporter.Light.cs, Maya/Exporter/BabylonExporter.Mesh.cs, Maya/Exporter/BabylonExporter.Node.cs
Fix issue #696 for Maya.
See PR #754 for 3dsMax.
ExportTransform method is used for lights and cameras as well as meshes:
1. for consistency
2. to update the rotation attribute of babylon objects. This way, the rotation is exported in glTF.
The ExportTransform method code is moved from Mesh.cs to Node.cs
=> [Maya] Fix light orientation in glTF

Maya/Exporter/BabylonExporter.CustomAttributes.cs, Maya/Exporter/BabylonExporter.Material.cs
Followup to discussion thread:
https://forum.babylonjs.com/t/maya-custom-attributes-with-arnold/8768/3
Tested and verified using scene:
[MayaMaterialCustomAttributes.zip](https://github.com/BabylonJS/Exporters/files/4251900/MayaMaterialCustomAttributes.zip)
This PR adds custom attribute support for Arnold and Stingray material export.
=> Adding support for exporting custom attributes added to stingray and arnold custom materials

3ds Max/Max2Babylon/Exporter/MaxGLTFMaterialExporter.cs, SharedProjects/Babylon2GLTF/GLTFExporter.Material.cs
See issue #766:
Support for the "hair and fur" world modifier was added to the Max2Babylon exporter. However, functionality was never extended to GLTFExporter.
In fact when trying to export from 3dsMax 2020 using the exporter to gltf or glb format, a NullReferenceException is thrown. 
Add check to gameMtl to prevent exception and the generate default material placeholder for the object with hair and fur.  There is additional work to be done to make this fully functional:
- Track, in memory the mapping of the base material that is applied to the model beneath the hair and fur world modifier.
- Wait for gltf extension support for hair and fur .
=> Patch for 3DSMax hair and fur modifier

Maya/Forms/ExporterForm.cs, SharedProjects/GltfExport.Entities/GLTFProperty.cs
removes 'Default Light' always being exported to gltf. removed serialization of empty scenes.extensions and scenes.extras object
Fixes #777
=> Remove Extra Serialized Bits

3ds Max/Max2Babylon/Exporter/BabylonExporter.Animation.cs, Maya/Exporter/BabylonExporter.Animation.cs, SharedProjects/Babylon2GLTF/GLTFExporter.Animation.cs, SharedProjects/BabylonExport.Entities/BabylonAnimationKey.cs, SharedProjects/BabylonExport.Entities/BabylonQuaternion.cs, SharedProjects/Utilities/MathUtilities.cs
This Pull Request adds logic to the keyframe exporting behavior of the maya animation exporter. Rotation animations with keyframe differences that exceed a certain threshold are interpolated linarly.
=> Fix maya animation rotation interpolation

Maya/Exporter/BabylonExporter.Mesh.cs
disable mesh optimization in this case as well.
=> Add warning with exporting optmimized mesh with morph targets.

3ds Max/Max2Babylon/Exporter/BabylonExporter.Mesh.cs, Maya/Exporter/BabylonExporter.Mesh.cs
Add check for ExportAnimations export flag when exporting morph target animation tracks
Fixes #778
=> Fix morph target animations being exported when ExportAnimations is disabed.

3ds Max/Max2Babylon/Exporter/BabylonExporter.Light.cs, Maya/Exporter/BabylonExporter.CustomAttributes.cs, Maya/Exporter/BabylonExporter.Light.cs, SharedProjects/BabylonExport.Entities/BabylonLight.cs
This PR makes multiple changes to the light and animation export pipelines to fix situations where lights with a child node are properly represented in scene. If a light in scene is animated, or contains a child node, then it will be encapsulated in a dummy node that will contain the animation or child node hierarchy.
Max implementation was introduced via #754, this PR addresses the same issue for Maya, and updated the Max implementation to use the same criteria.
=> Fix maya light orientation export

SharedProjects/Babylon2GLTF/GLTFExporter.Texture.cs
this PR inverts the texture vScale when using the KHR_texture_transform extension, due to babylon using a lower left texture coordinate origin, and glTF expecting a top left origin.
=> Fix KHR_texture_transform texture transform vScale

Maya/Exporter/BabylonExporter.Material.cs
fix for issue where textures are duplicated if a shared diffuse and opacity map is used.
=> [Maya] Fix texture duplication when shared opacity and diffuse maps are used.

Maya/Exporter/BabylonExporter.Animation.cs
Fix for issue where non-animated nodes are exported with useless animation tracks. added extra logic to IsAnimationKeysRelevant to take in a base value (ideally, the exported node value) and compare that against the key values, or a default value if not provided before keys are included in export
=> Fix animations being exported with useless tracks

SharedProjects/Babylon2GLTF/GLTFExporter.Mesh.cs
… via bitwise operation, changed intermediate values to be unsigned instead of signed, cleaned up bit shifting operations to flow better.
Fixes #810
=> Fix for gltf skin export with >128 bones. fixed skin index conversion

SharedProjects/Babylon2GLTF/GLTFExporter.Light.cs, SharedProjects/GltfExport.Entities/GLTFLight.cs, SharedProjects/Utilities/ArrayExtension.cs, SharedProjects/Utilities/MathUtilities.cs
Fix for issue where GLTF lights are serialized with improper field information in node declaration and lights declaration. updated default values for GLTFLight, updated ShouldSerialze field checks
Fixes #818
=> Fix GLTFLight serialization fields for node declaration, Fix GLTFLight defaults.

3ds Max/Max2Babylon/Exporter/BabylonExporter.CustomAttributes.cs
This fix changes the invoked 3ds Max Maxscript code used to setup a reference to the current processing IGameNode when exporting custom attributes.
Fixes #817
=> Fix for custom attribute serialization for 3dsMax IGameNodes

3ds Max/Max2Babylon/Exporter/BabylonExporter.Skeleton.cs
Fix for issue where skeletons are exported missing parent bone hierarchy, add nodes in hierarchy to world root to skeleton hierarchy
Fixes #823
=> Fix skeleton hierarchy export where parent bones are culled

Maya/Exporter/BabylonExporter.Animation.cs, SharedProjects/Babylon2GLTF/GLTFExporter.Animation.cs, SharedProjects/BabylonExport.Entities/BabylonAnimationKey.cs, SharedProjects/BabylonExport.Entities/BabylonQuaternion.cs, SharedProjects/Utilities/MathUtilities.cs
Fix for issue where animation tracks with no keyframes in the range are excluded from animation group inclusion. added animation track lerping between nearest animation frames for animation group range boundaries. modified glTF animtion group export to use exported babylon animation group tracks instead of node stored animation frames
Fixes #827
=> Fix Animation group exclusion of animation tracks with no keyframes in range.

3ds Max/Max2Babylon/2021/Max2Babylon2021.csproj, BabylonJS_Installer/BabylonJS_Installer/Properties/AssemblyInfo.cs
Change Max2021 release version compilation symbols. 
Update installer assembly version
=> more fixes to max 2021 tooling

BabylonJS_Installer/BabylonJS_Installer/Downloader.cs
this PR adds an installation warning to Maya2020 notifying the user to ensure that Maya2020.1 or later is installed.
=> Add version warning when installing maya 2020

3ds Max/Max2Babylon/Exporter/BabylonExporter.Mesh.cs
Fix was targeted towards 3dsMax scene:
[Forum_3dsmax-after-exporting-boolean-object-loses-its-texture.zip](https://github.com/BabylonJS/Exporters/files/4853658/Forum_3dsmax-after-exporting-boolean-object-loses-its-texture.zip)
https://forum.babylonjs.com/t/3dsmax-after-exporting-boolean-object-loses-its-texture/12004/3
Fix checks vertex color buffer for non-zero values, and only exports if a value is non-zero.
=> Added workaround for 3dsMax Boolean operation (and other similar operations) that assign null vertex color in-engine

Maya/Exporter/BabylonExporter.Animation.cs, SharedProjects/Babylon2GLTF/GLTFExporter.Animation.cs
Fix for issue where glTF exported animation groups only contained a single animation track per node. Fix addresses this by changing node animation-group track retrieval logic to retrieve all animation tracks for a given node instead of just the first.
Fixes #851
=> Fix animation tracks mising in gltf export

Maya/Exporter/BabylonExporter.cs, Maya/MayaPlugin.cs
Fix for issue where exporter hangs when invoked via MELScript. Remove Application.DoEvents() call from  MEL logging implementation and cancel callback
=> Fix Maya hangs when export is invoked via MELscript

Maya/Exporter/BabylonExporter.Skeleton.cs
Case that brought this up: comparing a joint named "head" to the full path of a joint named "forehead"
=> Fix substring comparison between full path of Maya joint and joint name

SharedProjects/Babylon2GLTF/GLTFExporter.Material.cs
When i exported several model with textures to one gltf model, the gltf model has a wrong material which has an extra `metallicRoughnessTexture` attribute, but i didn't add any specular textures. The gltf model as follow:
```json
"materials": [
{
"pbrMetallicRoughness": {
"baseColorTexture": {
"index": 0
},
"metallicFactor": 0,
"roughnessFactor": 0.450053632
},
"name": "01 - Default"
},
{
"pbrMetallicRoughness": {
"baseColorTexture": {
"index": 1
},
"metallicFactor": 0,
"roughnessFactor": 0.450053632
},
"name": "02 - Default"
},
{
"pbrMetallicRoughness": {
"baseColorTexture": {
"index": 1
},
"metallicRoughnessTexture": {
"index": 0
}
},
"name": "03 - Default"
}
],
```
The `03 - Default` material should be same with `02 - Default`.
I know the `optimizer` is used to merge materials with …
=> fix bug: extra "metallicRoughnessTexture"

Maya/Exporter/BabylonExporter.Mesh.cs, SharedProjects/Babylon2GLTF/GLTFExporter.Mesh.cs
Add mesh.extras.targetNames to gltf export.
Use "{blendShapeDeformer.name}.{currentWeightName}" as the name for babylonMorphTarget.
=> Export morph target names to GLTF

Maya/Exporter/BabylonExporter.Writer.cs, Maya/Maya2Babylon2020.csproj, SharedProjects/Utilities/JsonTextWriterOptimized.cs
Change the default json number precision from 4 to 8 to babylon file. fix #895, fix #869 
Clear unused/duplicated code into Maya/Exporter
=> Floating point precision to Babylon

SharedProjects/Babylon2GLTF/GLTFExporter.Texture.cs, SharedProjects/GltfExport.Entities/GLTFMaterial.cs, SharedProjects/Utilities/ArrayExtension.cs
Fix #872 default test behavior and prepare #892 support for clearcoat, sheen and transmission
=> KHR extensions

SharedProjects/Babylon2GLTF/GLTFExporter.cs
modify encoding to utf8 when export JSON for .glb format, then the exported glb model can support for languages other than english.
=> modify JSON export encoding to utf8 

3ds Max/Max2Babylon/Exporter/BabylonExporter.Texture.cs
Enhance the usage of Bump texture (do not need anymore to uncheck unused additional Bumb texture). Fix #906
=> fix bumpmap test

3ds Max/Max2Babylon/Exporter/BabylonExporter.Material.cs
=> Force Metal-Rought Factor to be 0 when no map

3ds Max/Max2Babylon/Exporter/AnimationGroup.cs, 3ds Max/Max2Babylon/Exporter/BabylonExporter.cs
Init the serialized ID of AnimationGroup when loading from properties. The bad initialization of the SerializedID prevent the MaxScript to work. This is related to this [question](https://forum.babylonjs.com/t/how-to-use-maxscript-to-add-animation-group-nodes/16836) from the forum.
=> Fix Animation Group

3ds Max/Max2Babylon/Exporter/BabylonExporter.cs
Max2Babylon added an empty node called “Default light”, even though the Babylon Scene Properties has the default light disabled
=> Use project default light property

3ds Max/Max2Babylon/Exporter/BabylonExporter.Mesh.cs
On Multi-Material, when user set it's own id, we must access the id using Max meshNode.NodeMaterial.GetMaterialID(i) instead of assign sequential index Fix #926
=> Add support for MaterialId on multiMaterial

3ds Max/Max2Babylon/Exporter/BabylonExporter.Material.cs
Add Specific Babylon Full PBR related attributes to PhysicalMaterial. fix #923.
Add Babylon/GLTF attribute to force the use of roughness or metallic factor even when map is set. "Use Scalar Factor". Related to this [topic](https://forum.babylonjs.com/t/how-to-use-the-pbrmaterial-metallic-property-in-3ds-max-export-to-glb/18187)
Layout the attribute to get a cleaner control
=> Add material specific attributes

3ds Max/Max2Babylon/Forms/ExporterForm.Designer.cs
for obscur reason, the logtreeview size has been reset to zero during previous PR. fix #934
=> set tree view size

3ds Max/Max2Babylon/Exporter/BabylonExporter.Texture.cs
When base color texture is null, add check to avoid exception and prevent exporter to stop.
This is related to [this ](https://forum.babylonjs.com/t/3dsmax-exporter-error-while-using-transparency-map/18854/3) forum discussion
=> 3DSMax Test BaseColorTexture for null

3ds Max/Max2Babylon/Exporter/BabylonExporter.Mesh.cs, 3ds Max/Max2Babylon/Exporter/GlobalVertex.cs, SharedProjects/Utilities/MathUtilities.cs
W Tangent calculation was impacted by floating point rounding error and generate inverted vector randomly. Fix #936
=> Update Tangent W calculation

3ds Max/Max2Babylon/Exporter/BabylonExporter.Mesh.cs
When any of object tangents are null and "use tangent" check box has been set, this was result into Object Null Exception. Fix #951
=> Null Tangent check

3ds Max/Max2Babylon/2015/Max2Babylon2015.csproj, 3ds Max/Max2Babylon/2015/Properties/Resources.Designer.cs, 3ds Max/Max2Babylon/2015/Properties/Resources.resx, 3ds Max/Max2Babylon/2017/Max2Babylon2017.csproj, 3ds Max/Max2Babylon/2017/Properties/Resources.Designer.cs, 3ds Max/Max2Babylon/2017/Properties/Resources.resx, 3ds Max/Max2Babylon/2018/Max2Babylon2018.csproj, 3ds Max/Max2Babylon/2018/Properties/Resources.Designer.cs, 3ds Max/Max2Babylon/2018/Properties/Resources.resx, 3ds Max/Max2Babylon/2019/Max2Babylon2019.csproj, 3ds Max/Max2Babylon/2019/Properties/Resources.Designer.cs, 3ds Max/Max2Babylon/2019/Properties/Resources.resx, 3ds Max/Max2Babylon/2020/Max2Babylon2020.csproj, 3ds Max/Max2Babylon/2020/Properties/Resources.Designer.cs, 3ds Max/Max2Babylon/2020/Properties/Resources.resx, 3ds Max/Max2Babylon/2021/Max2Babylon2021.csproj, 3ds Max/Max2Babylon/2021/Properties/Resources.Designer.cs, 3ds Max/Max2Babylon/2021/Properties/Resources.resx, 3ds Max/Max2Babylon/GlobalUtility.cs, 3ds Max/Max2Babylon/MaterialScripts.cs, 3ds Max/Max2Babylon/Scripts/BUMP_MAP_CAT_DEF.ms
3DSMAX : Add support for Babylon custom attributes for Normal Map. This prepare the ability to process the normal map according Babylon AND GLTF specification. Resolve #940
=> Add max bump properties to 3dsMax

3ds Max/Max2Babylon/Exporter/BabylonExporter.ExportItem.cs, 3ds Max/Max2Babylon/Exporter/BabylonExporter.Mesh.cs, 3ds Max/Max2Babylon/Exporter/BabylonExporter.cs, 3ds Max/Max2Babylon/Exporter/MaxExportParameters.cs, 3ds Max/Max2Babylon/Forms/ExporterForm.cs, 3ds Max/Max2Babylon/Forms/MultiExportForm.Designer.cs, 3ds Max/Max2Babylon/Forms/MultiExportForm.cs
According to #904 Introduce a new option in order to be able to do Multi-File Export without reseting the position pivot to origin. Fix #904.
=> 3dsMax : Add keep position option to multi export process.

3ds Max/Max2Babylon/Exporter/BabylonExporter.Material.cs, 3ds Max/Max2Babylon/Exporter/BabylonExporter.Texture.cs, 3ds Max/Max2Babylon/Exporter/MaxExportParameters.cs, SharedProjects/BabylonExport.Entities/ExportParameters.cs, SharedProjects/Utilities/Extensions.projitems, SharedProjects/Utilities/Texture/Operations/FlipChannel.cs, SharedProjects/Utilities/Texture/Operations/InvertY.cs, SharedProjects/Utilities/Texture/Operations/Normalize.cs, SharedProjects/Utilities/Texture/Operations/SwapChannel.cs, SharedProjects/Utilities/Texture/TextureOperation.cs, SharedProjects/Utilities/Texture/TextureUtilities.cs
Additional to previous #957 PR, finalize support for the NormalMap operation.
This allow, according to #940, to define the input format of the normal map and then allow the exporter to perform operations on the texture to export it in the correct format, targeting BabylonJS (directx) or GLTF (opengl). Resolve #940
=> 3DSMax bump map operation support

Maya/Exporter/BabylonExporter.Animation.cs, Maya/Exporter/BabylonExporter.Light.cs
Maya Light export has been suffering from setting a default animation  set which is pin the light as "dummy" node. Plus inconsistency with the direction when light is ponctual or ambient. fix #961
=> Fix Maya light export

3ds Max/Max2Babylon/MaterialScripts.cs, 3ds Max/Max2Babylon/Scripts/PHYSICAL_MATERIAL_CAT_DEF.ms
In some cases, when loading a scene, the new automatic way of adding custom attributes to Normal Bump leads to a stack overflow (mainly due to multi-threaded racing). In addition, this method was too cumbersome when a scene had a lot of material, degrading performance.
We modify this behavior by adding a specific button to the materials panel.
=> Fixes event issue on adding attribute to normalMaps

SharedProjects/Babylon2GLTF/GLTFExporter.Mesh.cs
In place scale has been left inside the code, when the scale is defined now at root level.
=> supress duplicate scale

3ds Max/Max2Babylon/BabylonAnimationActionItem.cs, 3ds Max/Max2Babylon/BabylonExportActionItem.cs, 3ds Max/Max2Babylon/BabylonLoadAnimations.cs, 3ds Max/Max2Babylon/BabylonPropertiesActionItem.cs, 3ds Max/Max2Babylon/BabylonSkipFlatten.cs, 3ds Max/Max2Babylon/BabylonStoreAnimations.cs
ActionItems was not available into ActionTable, because of duplicate Id (Id must be unique within an ActionTable). 
Prefix all related textual descriptions with "Babylon", in order to group the Items when editing with the Shortcut Key editor. Fix #974
=> Update Id and description of the action item

3ds Max/Max2Babylon/Exporter/BabylonExporter.Mesh.cs, 3ds Max/Max2Babylon/Forms/ObjectPropertiesForm.Designer.cs, 3ds Max/Max2Babylon/Forms/ObjectPropertiesForm.cs
fix #970 
The text is too wide, we must choose something else. Quick Export (draft) ?
=> Update Optimize Vertices label and checkbox behavior

SharedProjects/Babylon2GLTF/GLTFExporter.Texture.cs
the exporter warns about a disabled KHR_texture_transform when the bitmaps have no transforms applied.
VScale is set to -1 for Babylon export then the sign is flipped again for the Babylon2Gltf transformation.
However prior to this, the test for the KHR_TextureTransform was made against 1 for Babylon.VScale.
Also, we remove the duplicate warning message.
fix #986
=> correct KHR_TextureTransform warn

SharedProjects/Babylon2GLTF/GLTFExporter.Texture.cs, SharedProjects/Utilities/PathUtilities.cs
fix #985 
assuming the image name is a base file name 
We introduce local test to verify that the root path is not "./" nor "."
`./name.png` will become name.png
`./<path>/name.png` or other relative/absolute  path will stay same.
=> Discard local "relative" path to gltf image uri when located in same folder than model

3ds Max/Max2Babylon/Exporter/BabylonExporter.cs
When initialize the scene, use the "only selected" flag instead of systematic false
`              gameScene.InitialiseIGame(exportParameters.exportOnlySelected);
`
the result is the optimization of the scene export. We no longer have to go through all the nodes to test if they are selected.
When the scene encompasses thousands of meshes, it changes the game.  
fix #997
=> pass selected flags to scene initialization

3ds Max/Max2Babylon/Exporter/BabylonExporter.Mesh.cs
When "Optimize" mode is ON, the number of vertices may differ from source and target when using Morph. For the purpose, we rebuild systematically the Morph target to avoid such issues.
Note we MUST review the way that the framework is "optimizing" the vertices. The result is modify the original vertices  list and it's break the first exporter law, which is "do not modify the content". 
fix #999
=> Morph target VS optimize

3ds Max/Max2Babylon/Exporter/BabylonExporter.Texture.cs, SharedProjects/Babylon2GLTF/GLTFExporter.Texture.cs, SharedProjects/BabylonExport.Entities/BabylonMatrix.cs, SharedProjects/BabylonExport.Entities/BabylonVector3.cs, SharedProjects/Utilities/MathUtilities.cs
Giving the Max file into the following archive,
[KHR_Texture_transform.zip](https://github.com/BabylonJS/Exporters/files/7149511/KHR_Texture_transform.zip)
result are now coherent as you can see in .babylon and .gltf attached files.
Fix #1001.
MAX
BABYLON
GLTF
=> Texture transform support for both babylon and gltf format

3ds Max/Max2Babylon/Exporter/BabylonExporter.Animation.cs, 3ds Max/Max2Babylon/Exporter/BabylonExporter.Camera.cs, 3ds Max/Max2Babylon/Tools/Tools.cs
fix  #1003.
the bug was located into FixCamera methods where the transformation was applied to animation.keys which is a subset of animation.fullkeys. Then only a part of the keys was updated. By then reaching the AnimationGroup, the process relies on animation.fullkeys which was then no longer consistent. Note that animation optimization is done twice, one time when exporting the node and one time when exporting animation group.
=> Fix camera animation rotation issues

3ds Max/Max2Babylon/Exporter/BabylonExporter.Animation.cs, SharedProjects/BabylonExport.Entities/BabylonAnimationKey.cs
When 3DSMax user put a negative frame time into Animation, the exporter did not export the this animation correctly. We put a simple guard to limit the frame index to zero and avoid negative values. fix #1013.
=> 3DSMax exporter to avoid negative frame index for animation

Maya/Maya2Babylon2022.csproj
Trying to fix MAYA2022 deployment name issue. Seems character encoding was causing abort of the post build script.
=> fix Maya2022 post srcipt deloyment

3ds Max/Max2Babylon/Exporter/BabylonExporter.Skeleton.cs
Current version is NOT taking bone in account when single. This NOT fix the entire skeleton issues, but at least let people using a single bone to animate GLTF
see [this ](https://forum.babylonjs.com/t/skeleton-animation-in-3ds-max-will-not-export-to-glb/26121/9) forum post and also [this](https://forum.babylonjs.com/t/mesh-with-1-bone-from-3dsmax-causes-blank-scene/25390/9).
=> Save bone as relevant when single

3ds Max/Max2Babylon/Exporter/BabylonExporter.Mesh.cs
When rebuild the morph target from Delta values stored into Max SDK, we do NOT need to apply Transformation while the extracted data are already in World Coordinate.
=> Avoid Morph transform when rebuild

3ds Max/Max2Babylon/Exporter/BabylonExporter.Mesh.cs, 3ds Max/Max2Babylon/Exporter/BabylonExporter.Skeleton.cs
Add search down hierarchy to identify the presence of the skinned mesh and consequently select different Transformation matrix for the skeleton root (World, Local or Identity).
Before this only World and Identity were considered.
For BabylonJS, the Skeleton root cannot share a common ancestor with the mesh it own the skin, otherwize, the transformation is applied twice.
Therefore, Max is highly permissive regarding this point and allow ANY mesh to be a bone or part of the hierachy.
This PR fix this particular case.
=> Skin hierarchy

3ds Max/Max2Babylon/Exporter/BabylonExporter.Animation.cs, 3ds Max/Max2Babylon/Exporter/BabylonExporter.Skeleton.cs, SharedProjects/BabylonExport.Entities/BabylonAnimationKey.cs, SharedProjects/BabylonExport.Entities/BabylonMatrix.cs, SharedProjects/Utilities/MathUtilities.cs
Update root bone animation matrix according the one set into the bone.
The previous PR changed the bone matrix of the root, as appropriate for the hierarchy. However, we missed updating the animation matrix accordingly.
=> Update root bone animation matrix

SharedProjects/BabylonExport.Entities/BabylonAnimationKey.cs
according [this ](https://forum.babylonjs.com/t/maya-to-babylonjs-gltf-validation-error/28285/7)Forum thread,  for gltf offset the negative key frame instead of trim at zero.
=> Remove negative key frame guard at babylon level

SharedProjects/Utilities/Texture/TextureUtilities.cs
using common way of new Bitmap(path) is known as lock the ressource until disposed.
However, none of the object are disposed at the end of the export session (this might be another refactoring need). 
The solution is to change the way we load the image and use ImageConverter from byte [] instead of direct Bitmap linked with the underlying file.
- Pro is we are doing the change at one place only.
- Cons is we are still waste memory.
fix #1033
=> Change way to load bitmap from file

3ds Max/Max2Babylon/Exporter/BabylonExporter.Skeleton.cs, Maya/Exporter/BabylonExporter.Skeleton.cs
According to [this ](https://forum.babylonjs.com/t/meshes-with-skeletons-that-have-needinitialskinmatrix-true-crash-when-cloned/28247/9)forum thread, we remove the needInitialSkinMatrix  it was explicitely set to true.
Conducted test over few scene did not conclude to any regression so far.
=> remove needInitialSkinMatrix boolean set

Maya/Exporter/BabylonExporter.Mesh.cs
According to [this](https://forum.babylonjs.com/t/cannot-export-mesh-to-glb-with-both-morph-targets-and-skinning-in-maya-2022/28309/4) thread, modify the search to allow the exporter to search the graph down the skin.
=> Maya test SkinCluster and Set to find Blend into the graph

3ds Max/Max2Babylon/Exporter/BabylonExporter.Mesh.cs, SharedProjects/BabylonExport.Entities/BabylonMorphTarget.cs
According to [this ](https://forum.babylonjs.com/t/morphtargetmanagers-not-playing-animation-into-sandbox/27188/14) thread, update the code to leverage MorphManager auto-animation behavior of the Babylon SandBox (for Babylon format only)
=> 3DS Max Add autoAnimate related properties to Babylon MorphTarget Manager

3ds Max/Max2Babylon/Exporter/BabylonExporter.Mesh.cs, 3ds Max/Max2Babylon/Exporter/BabylonExporter.Skeleton.cs
Both Babylon and GLTF does need a root node for the skeleton, which mean that the minimum of join into a skeleton is 2. One of the reason is we need a fallback to address vertex who does not hold any join influence ( weight 1,0,0,0 to join 0 ).
3DSMax is more permissive and let user define a single join skin.
This PR fix this issue, adding a root in this case.
note : second pr version, forgot a commit into the remote branch.
=> Add root join when single bone skeleton

3ds Max/Max2Babylon/Exporter/BabylonExporter.Material.cs
This fixes a bug that occurs when there is no metal or roughness map but a metal or roughness factor other than 0. 
**Steps to reproduce the bug:**
1. Create a Physical Material
2. Link a metallic texture to the Metalness Map slot
3. Set Roughness factor to 0.8
4. Export
**Expected behaviour**
The exporter creates and merges a texture with color value 0.8 (204) in G-channel into the ORM/MR texture and sets the metalness and roughness factors to 1 because they are often used as texture weights (see e.g. Babylon.js Sandbox).
**Actual behaviour**
The exporter creates a correct ORM/MR texture with the given roughness value of 0.8 (204) in G-channel but sets the roughness factor to 0. Therefore, the roughness values in G-channel are completely ignored. The same happens exactly the other way …
=> Fix metal-rough factor when no map but metal-rough factor not 0

3ds Max/Max2Babylon/Exporter/BabylonExporter.Material.cs
Due to UI change, properties indices are not longer always valid for Material. 
This PR is a quick fix for bump level, but it MUST be extended for all the property that has been to be addressed by Name instead of index (which unlikely change between version).
=> Correct Bump Level property access for max 2023

3ds Max/Max2Babylon/Exporter/BabylonExporter.Animation.cs, SharedProjects/BabylonExport.Entities/BabylonQuaternion.cs
sometime, quaternion flip sign (using dual representation) and introduce discontinuity into the animation ( even if the value are valid rotation). This PR make the outcome more readable.
=> Quaternion animation fix

Maya/Maya2Babylon2017.csproj, Maya/Maya2Babylon2019.csproj, Maya/Maya2Babylon2020.csproj, Maya/Maya2Babylon2022.csproj, Maya/Maya2Babylon2023.csproj
Remove mandatory rename operation for Maya plug-in, by updating the build scripts.
=> Remove mandatory Maya rename operation 

3ds Max/Max2Babylon/Exporter/BabylonExporter.Material.cs
sometime the names of the material properties may changed - often is a third party plugin side effect with script material. 
so give a second chance with lowercase search to be more resilient.
for sample normal map will be now search using `"nomalMap"`, then `"normalmap"` and finally `" _NormalMap"`
remember that the last one is a fix for some 2022 version
fix #1072
=> add secondary lowercase test when looking for material property by name

3ds Max/Max2Babylon/Forms/ExporterForm.Designer.cs
Fixes #1097 , size of log tab was set to zero by previews PR.
=> Fixed broken log tab, UI size was set to zero by previews PR

SharedProjects/Babylon2GLTF/GLTFExporter.Animation.cs
Fixes #1093. 
Exporting animation groups with morph targets where not properly picking the correct BabylonMorphTargetManager based on the target animation id. The id was not been used in the query, resulting in always the first BabylonMorphTargetManager been selected multiple times.
=> Fixed issue with morph targets and animation groups.

3ds Max/Max2Babylon/Exporter/BabylonExporter.Mesh.cs
It looks like Max Script has some strange behavior regarding morph targets indexes. It does not start at 0 but if you ask for index 0 it returns the first element in the array. This was not been considerer when getting morph information from Max Script.
This fixes the following forum issue: https://forum.babylonjs.com/t/3ds-max-export-with-morph-attributes-missing-some-morph-attributes-targets/47051/8
=> Fixed morph targets to not be 0 index based

3ds Max/Max2Babylon/Exporter/BabylonExporter.Mesh.cs, 3ds Max/Max2Babylon/Exporter/GlobalVertex.cs
Increased number of UV Channels, to match the Maya Exporter
=> 3ds Max: 8 UV Channels

3ds Max/Max2Babylon/Exporter/BabylonExporter.Mesh.cs, 3ds Max/Max2Babylon/Forms/ExporterForm.Designer.cs, 3ds Max/Max2Babylon/Forms/ExporterForm.cs, 3ds Max/Max2Babylon/MaxScriptManager.cs, SharedProjects/BabylonExport.Entities/ExportParameters.cs
When exporting morph targets from 3DS Max, if the morph targets are already serialized into the scene the exporter will create morph targets using a naming convention ```$"{meshNode.Name}.morpher({m}).target({i})````. I'm adding an option in the exporter to allow users to keep the original morpher names in the exporter. This option will be off by default to avoid breaking compatibility with current behavior.
=> Add option to keep Morph targets names in 3DS Max

Maya/Exporter/BabylonExporter.Mesh.cs
It is possible that Maya returns a vector with values 0,0,0 when exporting tangent data for mesh.  If mesh has invalid model data we should not export it to avoid creating an invalid GLB. 
Fix #1131
=> Add check for invalid tangent data in Maya 

3ds Max/Max2Babylon/Exporter/BabylonExporter.Mesh.cs, 3ds Max/Max2Babylon/Exporter/BabylonExporter.cs, 3ds Max/Max2Babylon/Exporter/GlobalVertex.cs, 3ds Max/Max2Babylon/Forms/ExporterForm.cs, Maya/Exporter/BabylonExporter.Mesh.cs, Maya/Exporter/BabylonExporter.cs, Maya/Exporter/GlobalVertex.cs, Maya/Maya2Babylon.sln, SharedProjects/Babylon2GLTF/GLTFExporter.Mesh.cs, SharedProjects/Babylon2GLTF/GLTFGlobalVertex.cs, SharedProjects/BabylonExport.Entities/BabylonMesh.cs, SharedProjects/BabylonExport.Entities/BabylonScene.cs, SharedProjects/BabylonExport.Entities/BabylonVertexData.cs
GLTF allows bone indexes to be stored as 16 bit values, in our implementation we use a 32 bit integer to store 4 bones as bytes, this breaks the exporter for models that have more than 256 bones  even though they would be able to fit into a GLTF. I'm increasing our internal store of the bones to be done using 64bit integer to allow bones to be hold using 16bit, matching what is expected by GLTF.
=> Added support for 16bit bone indexes  
